import React, { useEffect, useState } from 'react'
import Head from "next/head";
import { useRouter } from 'next/router';
import Link from 'next/link';

const Orders = () => {
    const router = useRouter();
    const [orders, setOrders] = useState([])
    useEffect(() => {

        const fetchOrders = async () => {
            let a = await fetch(`${process.env.NEXT_PUBLIC_HOST}/api/myorders`, {
                method: 'POST',
                headers: {
                    'Content-type': 'application/json',
                },
                body: JSON.stringify({ token: JSON.parse(localStorage.getItem('myuser')).token })
            })
            let res = await a.json();
            setOrders(res.orders);
        }

        if (!localStorage.getItem('myuser')) {
            router.push('/')
        }
        else {
            fetchOrders();
        }

    }, [])
    return (
        <>
            <Head>
                <title>Codeswear - Orders</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className='container mx-auto min-h-screen'>
                <h1 className='font-semibold text-center p-8 text-2xl'>My Orders</h1>
                <div className="relative overflow-x-auto">
                    <table className="w-full text-sm text-left rtl:text-right text-gray-500 dark:text-gray-400">
                        <thead className="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
                            <tr>
                                <th scope="col" className="px-6 py-3">
                                    ID
                                </th>
                                <th scope="col" className="px-6 py-3">
                                    Email
                                </th>
                                <th scope="col" className="px-6 py-3">
                                    Price
                                </th>
                                <th scope="col" className="px-6 py-3">
                                    Details
                                </th>
                            </tr>
                        </thead>
                        <tbody>

                            {orders.map((item) => {

                                return <tr key={item._id} className="bg-white border-b dark:bg-gray-800 dark:border-gray-700 hover:bg-gray-100">
                                    <th scope="row" className="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white">
                                        {item.orderId}
                                    </th>
                                    <td className="px-6 py-4">
                                        {item.email}
                                    </td>
                                    <td className="px-6 py-4">
                                        {item.amount}
                                    </td>
                                    <td className="px-6 py-4">
                                        <Link href={'/order?id=' + item._id}>Details</Link>
                                    </td>
                                </tr>
                            })}




                        </tbody>
                    </table>
                </div>
            </div>
        </>
    )
}


export default Orders